# defaults: &defaults
#   host: localhost
#   # slaves:
#   #   - host: slave1.local
#   #     port: 27018
#   #   - host: slave2.local
#   #     port: 27019
# 
# development:
#   <<: *defaults
#   database: issue1240_development
# 
# test:
#   <<: *defaults
#   database: issue1240_test
# 
# # set these environment variables on your prod server
# production:
#   host: <%= ENV['MONGOID_HOST'] %>
#   port: <%= ENV['MONGOID_PORT'] %>
#   username: <%= ENV['MONGOID_USERNAME'] %>
#   password: <%= ENV['MONGOID_PASSWORD'] %>
#   database: <%= ENV['MONGOID_DATABASE'] %>

defaults: &defaults
  host: '127.0.0.1'
  autocreate_indexes: false
  allow_dynamic_fields: true
  include_root_in_json: false
  parameterize_keys: true
  persist_in_safe_mode: false
  raise_not_found_error: true
  reconnect_time: 3

development:
  <<: *defaults
  database: mo_development

test:
  <<: *defaults
  database: mo_test